name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Check documentation
      run: |
        # Check for broken links (basic check)
        find docs/_build/html -name "*.html" -exec grep -l "404" {} \; || true

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/

  keyword-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install GPG
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Generate keyword documentation
      run: |
        python -m robot.libdoc RobotFrameworkPGP keyword_docs.html

    - name: Upload keyword documentation
      uses: actions/upload-artifact@v3
      with:
        name: keyword-documentation
        path: keyword_docs.html